Repository HabitHive/front-react, pull requests merged in 2022-10, with the labels that each got.

#207 Css/tag weekbar
  src/components/common/ButtonStyle.jsx
  src/components/main/daily/MyTag.jsx
  src/components/main/daily/TodayTagList.jsx
  src/components/main/daily/WeekCalendar.jsx
  src/components/post/PostForm.jsx
  src/edit/EditForm.jsx
Labels: CSS

#208 습관 목록 CSS 변경 완료
  src/components/common/Header.jsx
  src/components/common/Tag.jsx
  src/components/mypage/ListModal.jsx
  src/components/mypage/Profile.jsx
  src/components/mypage/TagWeekday.jsx
  src/components/mypage/ToggleTags.jsx
  src/components/mypage/UserTags.jsx
  src/components/tagbuy/TagBuylist.jsx
  src/pages/MyPage.jsx
  src/pages/TagBuyPage.jsx
Labels: CSS

#209 #131 dailyPage - tagList 디자인 변경
  src/components/main/daily/DailyTag.jsx
  src/components/main/daily/TodayTagList.jsx
Labels: feature

#212 #131 dailyPage 일별목표,목표없을 때 글자크기 수정
  src/components/main/daily/DailyTag.jsx
  src/pages/MainDailyPage.jsx
Labels: CSS

#213 Dev
  src/components/main/daily/DailyTag.jsx
  src/pages/MainDailyPage.jsx
Labels: CSS

#214 css 수정
  src/components/common/Header.jsx
  src/components/mypage/ListModal.jsx
  src/components/mypage/UserTags.jsx
  src/components/tagbuy/TagBuylist.jsx
  src/components/tagbuy/TagLists.jsx
Labels: CSS

#215 #131 dialy Header 뿌연 이미지 수정 및 사이즈 재확인
  src/components/main/daily/WeekCalendar.jsx
  src/pages/MainDailyPage.jsx
Labels: CSS

#216 Dev
  src/components/common/Header.jsx
  src/components/main/daily/WeekCalendar.jsx
  src/components/mypage/ListModal.jsx
  src/components/mypage/UserTags.jsx
  src/components/tagbuy/TagBuylist.jsx
  src/components/tagbuy/TagLists.jsx
  src/pages/MainDailyPage.jsx
Labels: CSS

#217 #131 postPage , or-img
  public/index.html
  src/components/post/PostForm.jsx
Labels: CSS

#218 Dev
  public/index.html
  src/components/post/PostForm.jsx
Labels: CSS

#219 alert css 수정 및 리팩토링
  public/index.html
  src/axios/axios.js
  src/components/common/Alert.jsx
  src/components/common/AlertStyle.css
  src/components/common/LoginAlert.jsx
  src/components/login/LoginForm.jsx
  src/components/mypage/ListModal.jsx
  src/components/mypage/Profile.jsx
  src/components/mypage/UserTags.jsx
  src/components/pet/Pet.jsx
  src/components/signup/SignupForm.jsx
  src/components/survey/Category.jsx
  src/components/tagbuy/SelectBox.jsx
  src/components/tagbuy/TagBuyDrawer.jsx
Labels: CSS

#220 #131 customAlert 수정
  src/components/main/daily/TodayTagList.jsx
  src/components/post/PostForm.jsx
  src/edit/EditForm.jsx
Labels: CSS

#221 #131 today는 배경색다르게 표현, 클릭한 날짜는 다른 배경색으로 표현
  src/components/main/daily/WeekCalendar.jsx
  src/components/post/PostForm.jsx
  src/pages/MainDailyPage.jsx
Labels: CSS

#223 #222 mobile layout 개선
  src/components/common/GlobalStyle.jsx
  src/components/common/MobileLayout.jsx
  src/index.js
Labels: CSS

#225 #131 등록된 일정 수정시 endDate가 1일이 더 들어가는것 수정
  src/edit/EditForm.jsx
Labels: feature

#226 #131 postPage 에 태그박스 css 수정
  src/components/post/PostForm.jsx
Labels: CSS

#230 #131 에러텍스트 css 수정
  src/components/post/PostForm.jsx
Labels: CSS

#231 #131 postPage 버튼, edit 태그css와 버튼 css
  src/components/post/PostForm.jsx
  src/edit/EditForm.jsx
Labels: CSS

#232 Dev
  src/components/post/PostForm.jsx
  src/edit/EditForm.jsx
Labels: CSS

#233 #131 monthly 캘린더 밑 일별목표 위치 수정
  src/edit/EditForm.jsx
  src/pages/MonthlyPage.jsx
Labels: CSS

#234 Dev
  src/edit/EditForm.jsx
  src/pages/MonthlyPage.jsx
Labels: CSS

#235 CSS 및 예외 처리 추가
  src/components/common/Navbar.jsx
  src/components/mypage/UserTags.jsx
  src/components/pet/Pet.jsx
  src/components/tagbuy/TagBuyDrawer.jsx
  src/redux/modules/tagbuy.js
Labels: bug, CSS

#238 #237 monthly페이지에서는 나의 일별 목표의 습관수정/삭제/완료 불가
  src/components/main/daily/DailyTag.jsx
  src/components/main/daily/TodayTagList.jsx
  src/pages/MainDailyPage.jsx
  src/pages/MonthlyPage.jsx
Labels: feature

#239 Dev
  src/components/main/daily/DailyTag.jsx
  src/components/main/daily/TodayTagList.jsx
  src/pages/MainDailyPage.jsx
  src/pages/MonthlyPage.jsx
Labels: feature

#240 #30 monthlyPage - 헤더 및 캘린더 style, 잔디 구현
  src/assets/monthly/leftArrow.png
  src/assets/monthly/monthlyCalendarImg.png
  src/assets/monthly/rightArrow.png
  src/components/main/monthly/Calendar.css
  src/components/main/monthly/MonthlyCalendar.jsx
  src/pages/MonthlyPage.jsx
  src/redux/modules/month.js
Labels: feature

#243 #30 캘린더 코드 리팩토링
  src/components/main/monthly/MonthlyCalendar.jsx
  src/components/main/monthly/react-datepicker.css
Labels: CSS

#244 Dev
  src/components/main/monthly/MonthlyCalendar.jsx
  src/components/main/monthly/react-datepicker.css
Labels: CSS

#245 #30 캘린더 날짜구하기 함수식 정리
  src/components/main/monthly/MonthlyCalendar.jsx
Labels: refactoring

#246 Css/monthly calendar
  src/components/main/monthly/MonthlyCalendar.jsx
Labels: feature

#247 #30 코드 리팩토링
  src/components/main/monthly/MonthlyCalendar.jsx
Labels: refactoring

#248 Dev
  src/components/main/monthly/MonthlyCalendar.jsx
Labels: feature

#251 #237 일별목표 밑 색상 잘리는 부분 수정
  src/pages/MonthlyPage.jsx
  src/redux/modules/dailytag.js
Labels: CSS
