Repository HabitHive/front-react, pull requests merged in 2022-09, with the labels that each got.

#34 surveyPage 기능구현 완료
  src/axios/axios.js
  src/components/login/LoginForm.jsx
  src/components/signup/SignupForm.jsx
  src/components/survey/Category.jsx
  src/components/survey/CategoryBtn.jsx
  src/components/survey/categories.js
  src/pages/OnboardingPage.jsx
  src/shared/Router.jsx
Labels: feature

#43 #40 MyPage UserInfo 기능 구현 완료
  src/axios/axios.js
  src/axios/setToken.js
  src/components/common/Navbar.jsx
  src/components/login/LoginForm.jsx
  src/components/mypage/Profile.jsx
  src/components/mypage/UserTags.jsx
  src/components/signup/SignupForm.jsx
  src/index.js
  src/pages/MyPage.jsx
  src/pages/SurveyPage.jsx
  src/redux/modules/user.js
  src/redux/store/configStore.js
Labels: feature

#45 로딩화면 구현
  src/assets/spinner.gif
  src/components/common/Loading.jsx
  src/components/common/Navbar.jsx
  src/components/mypage/Profile.jsx
  src/components/mypage/UserTags.jsx
  src/pages/MyPage.jsx
Labels: enhancement, feature

#46 myPage 기능 구현 완료
  src/components/common/Loading.jsx
  src/components/mypage/TagWeekday.jsx
  src/components/mypage/ToggleTags.jsx
  src/components/mypage/UserTags.jsx
Labels: feature

#51 axios 작업 중
  package.json
  src/axios/axios.js
  src/axios/setToken.js
  src/components/login/LoginForm.jsx
  src/components/mypage/SubNav.jsx
  src/components/mypage/UserTags.jsx
  src/pages/MyPage.jsx
  src/redux/modules/user.js
  src/shared/Router.jsx
Labels: duplicate

#67 Feature/buy
  src/assets/onboardingTest.png
  src/components/login/LoginForm.jsx
  src/components/mypage/Profile.jsx
  src/components/mypage/UserTags.jsx
  src/components/onboarding/PageSlide.jsx
  src/components/signup/SignupForm.jsx
  src/components/tagbuy/TagBuyDrawer.jsx
  src/components/tagbuy/TagBuylist.jsx
  src/components/tagbuy/TagLists.jsx
  src/pages/OnboardingPage.jsx
  src/pages/TagBuyPage.jsx
  src/redux/modules/tagbuy.js
  src/redux/modules/user.js
  src/redux/store/configStore.js
  src/shared/Router.jsx
Labels: enhancement

#72 로그아웃 기능 구현
  src/components/common/Navbar.jsx
  src/components/mypage/SubNav.jsx
  src/components/mypage/UserTags.jsx
  src/redux/modules/tagbuy.js
  src/redux/modules/user.js
Labels: feature

#78 #76 CSS 작업 중
  src/assets/loadingImg/spinner.gif
  src/assets/loginImg/loginBG.png
  src/assets/loginImg/mainLogo.png
  src/assets/onboardingImg/carousel1.png
  src/assets/onboardingImg/carousel2.png
  src/components/common/Navbar.jsx
  src/components/common/SaveButtonLong.jsx
  src/components/login/LoginForm.jsx
  src/components/onboarding/carouselContents.js
  src/redux/modules/user.js
Labels: feature

#83 css 작업 중
  src/assets/mypageImg/userIMG.png
  src/assets/mypageImg/userPet1.png
  src/components/common/Layout.jsx
  src/components/common/Navbar.jsx
  src/components/mypage/Profile.jsx
  src/components/post/PostForm.jsx
  src/pages/PetPage.jsx
  src/redux/modules/tagbuy.js
  src/redux/modules/user.js
  src/shared/Router.jsx
Labels: bug, wontfix, feature

#84 buyPage 기능 구현 및 CSS
  src/assets/loginImg/loginBG.png
  src/assets/mypageImg/profileBG.png
  src/assets/mypageImg/userIMG.png
  src/assets/mypetImg/LV1.png
  src/assets/mypetImg/petBG.png
  src/components/common/Layout.jsx
  src/components/common/Navbar.jsx
  src/components/common/SaveButtonLong.jsx
  src/components/mypage/Profile.jsx
  src/components/mypage/SubNav.jsx
  src/components/mypage/ToggleTags.jsx
  src/components/mypage/UserTags.jsx
  src/components/pet/Pet.jsx
  src/components/pet/petData.js
  src/components/tagbuy/TagBuyDrawer.jsx
  src/components/tagbuy/TagBuylist.jsx
  src/components/tagbuy/TagLists.jsx
  src/pages/MyPage.jsx
  src/pages/PetPage.jsx
  src/redux/modules/mypage.js
  src/redux/modules/tagbuy.js
Labels: bug, enhancement, wontfix, feature

#88 에러 처리
  src/components/common/Alert.jsx
  src/components/mypage/TagWeekday.jsx
  src/components/tagbuy/TagBuyDrawer.jsx
  src/pages/TagBuyPage.jsx
  src/redux/modules/tagbuy.js
  src/redux/modules/user.js
Labels: wontfix

#92 온보딩 이미지 수정
  src/assets/onboardingImg/carousel3.png
  src/assets/onboardingImg/carousel4.png
  src/components/onboarding/carouselContents.js
  src/components/pet/Pet.jsx
  src/pages/TagBuyPage.jsx
Labels: documentation

#94 #52 pet Data 요청
  package.json
  src/App.js
  src/components/pet/Pet.jsx
  src/components/pet/ProgressBar.jsx
  src/pages/PetPage.jsx
  src/redux/modules/pet.js
  src/redux/modules/user.js
  src/redux/store/configStore.js
  src/shared/Router.jsx
  yarn.lock
Labels: wontfix

#95 #52 pet Data Thunk 처리
  src/App.js
  src/components/pet/Pet.jsx
  src/pages/NotFoundPage.jsx
  src/redux/modules/pet.js
  src/redux/modules/tagbuy.js
  src/redux/store/configStore.js
Labels: feature

#96 #52 petPage 구현 완료
  src/App.js
  src/assets/mypetImg/LV2.gif
  src/components/common/Alert.jsx
  src/components/pet/Pet.jsx
  src/components/pet/petData.js
  src/redux/modules/pet.js
  src/redux/modules/user.js
  src/shared/Router.jsx
Labels: feature

#98 CSS 수정
  src/App.js
  src/components/login/LoginForm.jsx
  src/components/pet/Pet.jsx
  src/components/pet/ProgressBar.jsx
  src/components/signup/SignupForm.jsx
  src/components/tagbuy/TagBuyDrawer.jsx
  src/components/tagbuy/TagBuylist.jsx
  src/redux/modules/pet.js
  src/redux/modules/user.js
Labels: documentation

#106 #105 로그인 방식 변경
  package.json
  src/App.js
  src/axios/axios.js
  src/axios/setSession.js
  src/axios/setToken.js
  src/components/common/LoginAlert.jsx
  src/components/login/LoginForm.jsx
  src/components/mypage/SubNav.jsx
  src/components/pet/Pet.jsx
  src/components/signup/SignupForm.jsx
  src/redux/modules/user.js
  src/shared/Router.jsx
  src/util/cookies.js
  yarn.lock
Labels: enhancement

#112 local HTTPS 적용
  .cert.pem
  key.pem
  package.json
  src/assets/mypageImg/profileBG.png
  src/axios/axios.js
  src/components/common/WeekCalTest.jsx
  src/components/mypage/Profile.jsx
Labels: enhancement

#122 로그인 로직 변경 (3차)
  package.json
  src/App.js
  src/axios/setSession.js
  src/axios/setToken.js
  src/components/common/GlobalStyle.jsx
  src/components/common/LoginAlert.jsx
  src/components/common/Navbar.jsx
  src/components/login/LoginForm.jsx
  src/components/mypage/ToggleTags.jsx
  src/components/mypage/UserTags.jsx
  src/components/signup/SignupForm.jsx
  src/redux/modules/mypage.js
  src/redux/modules/user.js
  src/shared/Router.jsx
  src/util/cookies.js
Labels: feature

#137 소셜로그인 수정
  src/components/common/Navbar.jsx
  src/components/common/SaveButtonLong.jsx
  src/components/login/LoginForm.jsx
  src/components/mypage/SubNav.jsx
  src/components/tagbuy/TagBuyDrawer.jsx
  src/redux/modules/mypage.js
  src/redux/modules/user.js
Labels: feature

#143 #135 예외처리 및 css 수정
  src/axios/axios.js
  src/components/mypage/ToggleTags.jsx
  src/components/mypage/UserTags.jsx
  src/redux/modules/mypage.js
Labels: CSS

#145 error 수정
  src/axios/axios.js
Labels: feature

#148 로그인 로그아웃 로직 수정
  src/App.js
  src/components/login/LoginForm.jsx
  src/components/mypage/SubNav.jsx
  src/redux/modules/user.js
  src/shared/Router.jsx
Labels: feature

#150 css 수정
  src/components/common/Navbar.jsx
  src/components/mypage/SubNav.jsx
  src/redux/modules/user.js
Labels: CSS

#162 #159 게이미피케이션 요소 추가
  src/assets/mypetImg/cursor.cur
  src/components/login/LoginForm.jsx
  src/components/pet/Pet.jsx
  src/redux/modules/pet.js
Labels: enhancement

#172 buyPage 예외처리 추가
  src/assets/loadingImg/loadingBG.png
  src/assets/loadingImg/spinner.gif
  src/components/common/Loading.jsx
  src/components/mypage/Profile.jsx
  src/components/tagbuy/TagBuyDrawer.jsx
  src/redux/modules/tagbuy.js
Labels: feature

#174 #171 에러 수정
  src/components/tagbuy/TagBuyDrawer.jsx
Labels: feature

#181 레이아웃 변경
  public/index.html
  src/components/common/GlobalStyle.jsx
  src/components/common/Layout.jsx
  src/components/common/Navbar.jsx
  src/components/mypage/SubNav.jsx
  src/components/mypage/UserTags.jsx
Labels: CSS

#188 UT용 2차 배포
  package.json
  public/index.html
  src/assets/mypageImg/profileBG.png
  src/assets/mypetImg/petBG.png
  src/axios/axios.js
  src/components/common/GlobalStyle.jsx
  src/components/common/Layout.jsx
  src/components/common/Navbar.jsx
  src/components/common/SaveButton.jsx
  src/components/common/SaveButtonLong.jsx
  src/components/login/LoginForm.jsx
  src/components/main/daily/MyTag.jsx
  src/components/main/daily/TodayTagList.jsx
  src/components/main/daily/WeekCalendar.jsx
  src/components/mypage/Profile.jsx
  src/components/mypage/SubNav.jsx
  src/components/mypage/UserTags.jsx
  src/components/onboarding/Carousel.jsx
  src/components/onboarding/carouselContents.js
  src/components/pet/Pet.jsx
  src/components/post/PostForm.jsx
  src/components/post/RepeatDay.jsx
  src/components/tagbuy/RandomTagList.jsx
  src/components/tagbuy/TagBuyDrawer.jsx
  src/components/tagbuy/TagBuylist.jsx
  src/components/tagbuy/TagLists.jsx
  src/edit/EditForm.jsx
  src/edit/EditRepeat.jsx
  src/pages/MainDailyPage.jsx
  src/pages/MyPage.jsx
  src/pages/OnboardingPage.jsx
  src/redux/modules/schedule.js
  src/redux/modules/tagbuy.js
  src/shared/Router.jsx
  yarn.lock
Labels: bug, enhancement, feature, CSS

#189 #159 petPage 게이미피케이션 추가
  public/index.html
  src/axios/axios.js
  src/components/common/GlobalStyle.jsx
  src/components/pet/Pet.jsx
  src/components/pet/petData.js
  src/redux/modules/tagbuy.js
Labels: feature, CSS

#192 #159 에러 수정
  src/redux/modules/pet.js
Labels: feature, CSS

#201 #131 디자인 피드백에 맞게 등록,수정페이지 css 수정
  src/assets/main/maincalendar.png
  src/components/post/PostForm.jsx
  src/components/post/RepeatDay.jsx
  src/edit/EditForm.jsx
  src/edit/EditRepeat.jsx
Labels: CSS

#204 Feature/fixed
  src/assets/buyImg/buyBG.png
  src/assets/mypageImg/LV1.png
  src/assets/mypageImg/LV2.png
  src/assets/mypageImg/LV3.png
  src/assets/mypageImg/LV4.png
  src/assets/tag/icon0.png
  src/assets/tag/icon1.png
  src/assets/tag/icon2.png
  src/assets/tag/icon3.png
  src/assets/tag/mask0.png
  src/assets/tag/mask1.png
  src/assets/tag/mask2.png
  src/assets/tag/mask3.png
  src/components/common/ButtonStyle.jsx
  src/components/common/Tag.jsx
  src/components/login/LoginForm.jsx
  src/components/mypage/Profile.jsx
  src/components/mypage/SubNav.jsx
  src/components/mypage/ToggleTags.jsx
  src/components/mypage/UserTags.jsx
  src/components/onboarding/Carousel.jsx
  src/components/onboarding/carouselContents.js
  src/components/pet/Pet.jsx
  src/components/signup/SignupForm.jsx
  src/components/survey/Category.jsx
  src/components/tagbuy/RandomTagList.jsx
  src/components/tagbuy/SelectBox.jsx
  src/components/tagbuy/TagBuyDrawer.jsx
  src/components/tagbuy/TagBuylist.jsx
  src/pages/NotFoundPage.jsx
  src/pages/TagBuyPage.jsx
  src/redux/modules/tagbuy.js
  src/redux/modules/user.js
  src/shared/Router.jsx
Labels: enhancement, feature, CSS

#205 라우팅 수정
  src/components/mypage/SubNav.jsx
  src/components/onboarding/Carousel.jsx
  src/components/signup/SignupForm.jsx
  src/components/survey/Category.jsx
  src/pages/OnboardingPage.jsx
  src/pages/SurveyPage.jsx
Labels: feature
